version: '3.8'

services:
  t5server:
    build: .
    container_name: t5server
    ports:
      - "28960:28960/udp"  # T5 Server Port (UDP)
    volumes:
      - t5server_data:/root/T5Server
    env_file:
      - .env
    restart: unless-stopped

volumes:
  t5server_data:
